version: '3.8'
services:
  web:
    # image: nginx
    build: ./
    volumes:
      - ../html/:/usr/share/nginx/html
      - ../.git/:/usr/share/nginx/.git
      - ./:/usr/share/nginx/.devcontainer
      - ./../.gitignore:/usr/share/nginx/.gitignore

    ports:
      - "8180:80"
      - "8181:81"